# PROFILE_APP_NAME = None
# PROFILE_MODEL_NAME = None

# COMMENT_USE_GRAVATAR = False

COMMENT_URL_PREFIX = 'comment-'
COMMENT_URL_SUFFIX = ''
COMMENT_URL_ID_LENGTH = 8
COMMENT_PER_PAGE = 10

COMMENT_ORDER_BY = ['-posted']

COMMENT_WRAP_CONTENT_WORDS = 30

# COMMENT_DEFAULT_PROFILE_PIC_LOC = '/static/img/default.png'
