COMMENT_URLHASH_LENGTH = 8

COMMENT_STATUS_CHECK = False

COMMENT_OFFLINE_IMPORTS = True

COMMENT_PROFILE_IMAGE_FIELD = None
COMMENT_PROFILE_IMAGE_DEFAULT = 'img/profile.png'

COMMENT_ALLOW_SPOILER = True
COMMENT_ALLOW_REPLY = True
COMMENT_ALLOW_EDIT = True
COMMENT_ALLOW_DELETE = True

# COMMENT_PER_PAGE = 10

# COMMENT_ORDER_BY = ['-posted']

# COMMENT_WRAP_CONTENT_WORDS = 30
