from django.conf import settings

_COMMENTS_SETTINGS = getattr(settings, "COMMENTS_SETTINGS", {})

COMMENTS_SETTINGS = {
    'LOGIN_URL': getattr(settings, 'LOGIN_URL'),
    'LANGUAGE_CODE': getattr(settings, 'LANGUAGE_CODE'),
    'URLHASH_LENGTH': _COMMENTS_SETTINGS.get('URLHASH_LENGTH', 8),
    'OFFLINE_IMPORTS': _COMMENTS_SETTINGS.get('OFFLINE_IMPORTS', True),
    'PROFILE_IMAGE_FIELD': _COMMENTS_SETTINGS.get('PROFILE_IMAGE_FIELD', None),
    'PROFILE_IMAGE_DEFAULT': _COMMENTS_SETTINGS.get('PROFILE_IMAGE_DEFAULT', 'img/profile.png'),
}
