# Generated by Django 4.1.7 on 2023-02-15 12:19

from django.db import migrations


def InitialCommentSettings(apps, schema_editor):
    CommentSettings = apps.get_model('comment', 'CommentSettings')
    CommentSettings.objects.create(name='Default Config', slug='default-config')


def InitialReact(apps, schema_editor):
    React = apps.get_model('comment', 'React')
    React.objects.create(slug='like', emoji='👍')
    React.objects.create(slug='dislike', emoji='👎')


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(InitialCommentSettings),
        migrations.RunPython(InitialReact),
    ]
